'use client';

import { useState, useCallback } from 'react';
import { createClient } from '@/lib/supabase/client';
import { UserSettings } from './useUserSettings';
import { EmergencyContact } from './useEmergencyContacts';
import { UserLocation } from './useUserLocation';

export interface Hospital {
  name: string;
  address: string;
  phone?: string;
  distance: number;
}

interface AlertInfo {
  type: string;
  severity: string;
  timestamp: Date;
  location?: UserLocation | null;
}

export interface DispatchResult {
  success: boolean;
  notified911: boolean;
  notifiedContacts: EmergencyContact[];
  notifiedHospital: Hospital | null;
  mailtoOpened: boolean;
  alertId?: string;
}

// ---------------------------------------------------------------------------
// Build a mailto: URL with pre-filled subject + body
// ---------------------------------------------------------------------------
function buildMailtoUrl(
  emails: string[],
  alertInfo: AlertInfo,
  location: UserLocation | null,
  hospital: Hospital | null,
): string {
  const time = alertInfo.timestamp.toLocaleString();

  const subject = `SentinelCare CRITICAL ALERT - ${alertInfo.type}`;

  const lines: string[] = [
    'SENTINELCARE EMERGENCY ALERT',
    '================================',
    '',
    `Event:       ${alertInfo.type}`,
    `Severity:    ${alertInfo.severity.toUpperCase()}`,
    `Detected at: ${time}`,
  ];

  if (location?.home_address) {
    lines.push(`Location:    ${location.home_address}`);
  }
  if (location?.latitude && location?.longitude) {
    lines.push(`Map:         https://www.google.com/maps?q=${location.latitude},${location.longitude}`);
  }

  if (hospital) {
    lines.push('');
    lines.push('NEAREST HOSPITAL');
    lines.push('================================');
    lines.push(`Name:        ${hospital.name}`);
    lines.push(`Address:     ${hospital.address}`);
    if (hospital.phone) {
      lines.push(`Phone:       ${hospital.phone}`);
    }
    lines.push(`Distance:    ${hospital.distance} mi`);
    if (location?.latitude && location?.longitude) {
      lines.push(
        `Directions:  https://www.google.com/maps/dir/${location.latitude},${location.longitude}/${encodeURIComponent(hospital.address)}`
      );
    }
  }

  lines.push('');
  lines.push('================================');
  lines.push('This alert was generated by SentinelCare.');
  lines.push('Please check on the person immediately or call emergency services.');

  const body = lines.join('\n');
  const to = emails.join(',');

  return `mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:8000';

export function useAlertDispatch() {
  const [dispatching, setDispatching] = useState(false);
  const [lastDispatch, setLastDispatch] = useState<DispatchResult | null>(null);
  const supabase = createClient();

  // Fetch nearest hospital based on location
  const fetchNearestHospital = useCallback(async (lat: number, lng: number): Promise<Hospital | null> => {
    try {
      const response = await fetch('/api/nearby-hospitals', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ latitude: lat, longitude: lng }),
      });

      if (!response.ok) return null;

      const data = await response.json();
      return data.hospitals?.[0] || null;
    } catch (err) {
      console.error('Error fetching nearest hospital:', err);
      return null;
    }
  }, []);

  // Push contacts + location to backend so it can auto-send emails on alert
  const syncAlertConfig = useCallback(async (
    contacts: EmergencyContact[],
    location: UserLocation | null,
    nearestHospital: Hospital | null,
  ) => {
    try {
      const payload = {
        contacts: contacts
          .filter(c => c.email && c.email.trim())
          .map(c => ({ name: c.name, email: c.email, phone: c.phone })),
        location: location
          ? {
              address: location.home_address || '',
              latitude: location.latitude,
              longitude: location.longitude,
            }
          : {},
        nearest_hospital: nearestHospital
          ? {
              name: nearestHospital.name,
              address: nearestHospital.address,
              phone: nearestHospital.phone || '',
              distance: nearestHospital.distance,
            }
          : null,
      };

      await fetch(`${BACKEND_URL}/alerts/config`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
    } catch (err) {
      console.error('Error syncing alert config to backend:', err);
    }
  }, []);

  // Main dispatch function
  const dispatchAlert = useCallback(async (
    alertInfo: AlertInfo,
    settings: UserSettings | null,
    contacts: EmergencyContact[],
    location: UserLocation | null
  ): Promise<DispatchResult> => {
    setDispatching(true);

    const result: DispatchResult = {
      success: false,
      notified911: false,
      notifiedContacts: [],
      notifiedHospital: null,
      mailtoOpened: false,
    };

    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error('Not authenticated');

      // 1. Fetch nearest hospital when the option is checked
      let nearestHospital: Hospital | null = null;
      if (location?.latitude && location?.longitude && settings?.notify_nearest_hospital) {
        nearestHospital = await fetchNearestHospital(
          Number(location.latitude),
          Number(location.longitude)
        );
        if (nearestHospital) {
          result.notifiedHospital = nearestHospital;
        }
      }

      // 2. Flag 911 intent
      if (settings?.notify_911) {
        console.log('[ALERT DISPATCH] 911 flag set:', {
          location: location?.home_address,
          issue: alertInfo.type,
          time: alertInfo.timestamp.toISOString(),
        });
        result.notified911 = true;
      }

      // 3. Email emergency contacts via mailto:
      if (settings?.notify_emergency_contacts && contacts.length > 0) {
        result.notifiedContacts = contacts;

        const emailAddresses = contacts
          .map(c => c.email?.trim())
          .filter((e): e is string => !!e && e.length > 0);

        if (emailAddresses.length > 0) {
          const url = buildMailtoUrl(emailAddresses, alertInfo, location, nearestHospital);
          window.open(url, '_blank');
          result.mailtoOpened = true;
        }
      }

      // 4. Log alert to database
      const { data: alertData, error: alertError } = await supabase
        .from('alert_history')
        .insert({
          user_id: user.id,
          alert_type: alertInfo.type,
          severity: alertInfo.severity,
          location_address: location?.home_address || null,
          latitude: location?.latitude || null,
          longitude: location?.longitude || null,
          triggered_at: alertInfo.timestamp.toISOString(),
          notified_911: result.notified911,
          notified_contacts: result.notifiedContacts.map(c => ({ name: c.name, phone: c.phone, email: c.email })),
          notified_hospital: result.notifiedHospital?.name || null,
          status: 'dispatched',
        })
        .select()
        .single();

      if (alertError) {
        console.error('Error logging alert:', alertError);
      } else {
        result.alertId = alertData.id;
      }

      result.success = true;
      setLastDispatch(result);
      return result;
    } catch (err) {
      console.error('Error dispatching alert:', err);
      return result;
    } finally {
      setDispatching(false);
    }
  }, [supabase, fetchNearestHospital]);

  // Cancel/acknowledge an alert
  const acknowledgeAlert = useCallback(async (alertId: string) => {
    try {
      const { error } = await supabase
        .from('alert_history')
        .update({
          acknowledged_at: new Date().toISOString(),
          status: 'acknowledged',
        })
        .eq('id', alertId);

      if (error) throw error;
    } catch (err) {
      console.error('Error acknowledging alert:', err);
    }
  }, [supabase]);

  return {
    dispatching,
    lastDispatch,
    dispatchAlert,
    acknowledgeAlert,
    fetchNearestHospital,
    syncAlertConfig,
  };
}
